export const actionTypes = {
    FETCHING_START : 'FETCHING_START',
    FETCHING_SUCCESS : 'FETCHING_SUCCESS',
    APPLIED_POST_FETCHING_SUCCESS : 'APPLIED_POST_FETCHING_SUCCESS',
    FETCHING_ERROR : 'FETCHING_ERROR',

}

export const APPLY_POST = 'APPLY_POST'